-- Authored route sequence: each section starts/ends on a safe checkpoint island.
-- Width, rise, length and bend are authored independently; no endless random map.
return {
    Coast = {
        {name="Первые обороты",kind="road",length=90,width=22,rise=0,turn=0},
        {name="Променад",kind="slalom",length=110,width=20,rise=0,turn=0},
        {name="Мост к причалу",kind="bridge",length=90,width=12,rise=6,turn=0},
        {name="Первый отрыв",kind="gaps",length=96,width=18,rise=0,turn=0},
        {name="Вверх на крыши",kind="road",length=100,width=18,rise=22,turn=0},
        {name="Поворот у кафе",kind="curve",length=90,width=17,rise=0,turn=60},
        {name="Солнечные панели",kind="slalom",length=110,width=18,rise=0,turn=0},
        {name="Узкий карниз",kind="bridge",length=90,width=8,rise=4,turn=0},
        {name="Ветряная станция",kind="sweeper",length=100,width=20,rise=0,turn=0},
        {name="Двойной прыжок",kind="gaps",length=110,width=16,rise=0,turn=0},
        {name="Над набережной",kind="curve",length=100,width=14,rise=6,turn=-70},
        {name="Финиш у маяка",kind="road",length=100,width=24,rise=-10,turn=0},
    },
    Garden = {
        {name="Терраса",kind="road",length=95,width=20,rise=12,turn=0},
        {name="Бамбуковая аллея",kind="slalom",length=120,width=19,rise=0,turn=0},
        {name="Мост облаков",kind="bridge",length=110,width=9,rise=10,turn=0},
        {name="Острова",kind="gaps",length=105,width=16,rise=0,turn=0},
        {name="Спираль сада",kind="curve",length=130,width=13,rise=20,turn=80},
        {name="Тихая терраса",kind="road",length=80,width=22,rise=0,turn=0},
        {name="Вращение",kind="sweeper",length=110,width=19,rise=0,turn=0},
        {name="Листопад",kind="slalom",length=115,width=17,rise=10,turn=0},
        {name="Небесная нить",kind="bridge",length=110,width=7,rise=0,turn=0},
        {name="Ступени ветра",kind="gaps",length=114,width=14,rise=0,turn=0},
        {name="Серпантин",kind="curve",length=115,width=12,rise=8,turn=-90},
        {name="Сад рассвета",kind="road",length=100,width=24,rise=0,turn=0},
    },
    Metro = {
        {name="Ночная смена",kind="road",length=100,width=20,rise=8,turn=0},
        {name="Сервисный тоннель",kind="slalom",length=125,width=17,rise=0,turn=0},
        {name="Магистраль",kind="curve",length=130,width=13,rise=14,turn=-75},
        {name="Разрыв линии",kind="gaps",length=120,width=14,rise=0,turn=0},
        {name="Антенны",kind="sweeper",length=110,width=18,rise=0,turn=0},
        {name="Стальная нить",kind="bridge",length=115,width=6,rise=12,turn=0},
        {name="Смена высоты",kind="road",length=110,width=16,rise=25,turn=0},
        {name="Красный сектор",kind="slalom",length=120,width=16,rise=0,turn=0},
        {name="Час пик",kind="sweeper",length=110,width=17,rise=0,turn=0},
        {name="Последний отрыв",kind="gaps",length=120,width=12,rise=0,turn=0},
        {name="Орбита",kind="curve",length=140,width=11,rise=10,turn=100},
        {name="Над городом",kind="road",length=105,width=24,rise=0,turn=0},
    },
}
